spring.application.name=banco_api
spring.datasource.url=jdbc:postgresql://localhost:5432/banco-api-pvf
spring.datasource.username=postgres
spring.datasource.password=posthabbgres16
spring.datasource.driver-class-name=org.postgresql.Driver